#
#    Copyright 2017 EPAM Systems
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
FROM {{DOCKER_BASE_IMAGE}}

# Standard set up Nginx
ENV NGINX_VERSION 1.13.7-1~stretch
ENV NJS_VERSION   1.13.7.0.1.15-1~stretch

RUN set -x \
	&& apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y nginx libpcre3 libpcre3-dev

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 5000

# Install uWSGI
RUN pip install uwsgi

# Make NGINX run on the foreground
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

COPY nginx.conf /etc/nginx/conf.d/
COPY uwsgi.ini /etc/uwsgi/

RUN apt-get update && apt-get install -y supervisor
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

ENV UWSGI_INI /usr/local/lib/python3.5/dist-packages/legion/uwsgi.ini

ENV NGINX_MAX_UPLOAD 0

ENV LISTEN_PORT 5000

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

COPY app_uwsgi.ini /usr/local/lib/python3.5/dist-packages/legion/uwsgi.ini
RUN rm /etc/nginx/sites-enabled/default

CMD ["/usr/bin/supervisord"]

ADD {{MODEL_FILE}} "/legion/{{MODEL_FILE}}"

{% for PIP_INSTALL_TARGET in PIP_INSTALL_TARGETS %}

{% if PIP_CUSTOM_TARGET %}
ADD {{PIP_INSTALL_TARGET}} "/legion/{{PIP_INSTALL_TARGET}}"
RUN pip3 install /legion/{{PIP_INSTALL_TARGET}}
{% else %}
RUN pip3 install {{PIP_REPOSITORY}} {{PIP_INSTALL_TARGET}}
{% endif %}

{% endfor %}

ENV MODEL_FILE="/legion/{{MODEL_FILE}}" \
    MODEL_ID="{{MODEL_ID}}" \
    GUNICORN_WORKER_CLASS="aiohttp.worker.GunicornWebWorker" \
    GUNICORN_WORKER_COUNT="1" \
    GUNICORN_WORKER_PATH="legion.serving.wsgi_aio:aioapp" \
    VERBOSE="false"
