node {
    def legion = load legion()

    legion.pod(ram: '1Gi') {
        stage('clone repo'){
            checkout scm
        }
        
        stage('run script'){
            sh '''
            chmod a+rwx /app
            '''
            legion.runScript('train.py')
        }

        stage('build'){
            legion.build()
        }

        stage('deploy'){
            legion.deploy(livenesstimeout: 15, readinesstimeout: 15)
        }
    }
}
